# Generated by Django 4.2.2 on 2024-10-31 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 - Очень плохо'), (2, '2 - Плохо'), (3, '3 - Нормально'), (4, '4 - Хорошо'), (5, '5 - Отлично')], default=5, verbose_name='Рейтинг'),
        ),
    ]
