# Generated by Django 4.2.2 on 2024-11-14 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_alter_review_creation_date_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryOfOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название страны')),
            ],
            options={
                'verbose_name': 'Страна происхождения',
                'verbose_name_plural': 'Страны происхождения',
            },
        ),
        migrations.AlterField(
            model_name='model_and_tochka',
            name='country_of_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.countryoforigin', verbose_name='Страна производителя'),
        ),
    ]
