# Generated by Django 4.2.2 on 2024-11-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_countryoforigin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('publication_date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='news_photos/%Y/%m/%d', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-publication_date'],
            },
        ),
    ]
