# Generated by Django 4.2.2 on 2024-11-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_and_tochka',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество на складе'),
        ),
        migrations.AlterField(
            model_name='model_and_tochka',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна производителя'),
        ),
    ]
