# Generated by Django 4.2.2 on 2024-11-14 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_model_and_tochka_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_and_tochka',
            name='country_of_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.countryoforigin', verbose_name='Страна производителя'),
        ),
    ]
