# Generated by Django 4.2.2 on 2024-11-15 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0016_actionhistory_delete_useraction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionhistory',
            options={},
        ),
        migrations.AlterField(
            model_name='actionhistory',
            name='action_type',
            field=models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление')], max_length=10, verbose_name='Тип действия'),
        ),
        migrations.AlterField(
            model_name='actionhistory',
            name='details',
            field=models.TextField(verbose_name='Детали'),
        ),
        migrations.AlterField(
            model_name='actionhistory',
            name='model_name',
            field=models.CharField(max_length=100, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='actionhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время действия'),
        ),
        migrations.AlterField(
            model_name='actionhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
