# Generated by Django 4.2.2 on 2024-11-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_alter_actionhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionhistory',
            name='model_name',
            field=models.CharField(max_length=50, verbose_name='Модель'),
        ),
    ]
