# Generated by Django 4.2.2 on 2024-11-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_alter_actionhistory_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionhistory',
            name='model_name',
            field=models.CharField(max_length=100, verbose_name='Модель'),
        ),
    ]
